# Generated by Django 4.1.7 on 2023-03-12 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import puzzle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=puzzle.models.default_number)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('pub_date', models.DateTimeField(default=puzzle.models.default_pub_date, verbose_name='publication date')),
                ('size', models.IntegerField(default=15, editable=False)),
                ('type', models.IntegerField(choices=[(0, 'Blocked'), (1, 'Barred')], default=0, editable=False)),
                ('user', models.ForeignKey(default=puzzle.models.default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=30)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('down', models.BooleanField(choices=[(True, 'Down'), (False, 'Across')], default=False, verbose_name='direction')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle.puzzle')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
