# Generated by Django 4.1.7 on 2023-03-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='weight',
            field=models.IntegerField(default=5),
        ),
    ]
