# Generated by Django 4.1.7 on 2023-03-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_entry_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_entries', to='puzzle.puzzle'),
        ),
    ]
